# 1 ---JOB TEST---
# name: CI Pipeline: Pipeline-ın adıdır,GitHub Actions səhifəsində bunu görürük
# jobs: Burada pipeline hansı işləri görəcəyini yazırıq.(Məs:Məndə iki jobs var test və docker-build)
# runs-on: github mənim üçün müvəqqəti ubuntu serveri açır və kodu işlədir
# env: Buradakı dəyişənlər pipeline işləyən zaman istifadə olunur,Github secretsdən oxunur
# steps: jobun addımlarıdır
# uses: GitHub repository-ni virtual maşına yükləyir,   GitHub Repo ---> Ubuntu Server
# setup-java@v4: java quraşdırılır
# if: always(): Bu o deməkdir ki,Test uğurlu olsada uğursuz olsada bu addım işləyəcək
# actions/upload-artifact: Test nəticələrini Githuba yüklüyür

# 2 ---JOB DOCKER-BUILD---
# needs: test ,Əvvəl test bitməlidir. Sonra docker-build başlaya bilər,Əgər test uğursuz olsa başlamayacaq
# docker build -t excermol:${{ github.sha }} .: Bu docker image yaradır. github.sha isə hər commit üçün unikal image yaradır.(Məs:excermol:3af7bdb1)

name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
      JWT_EXPIRATION: ${{ secrets.JWT_EXPIRATION }}
      JWT_REFRESH_EXPIRATION: ${{ secrets.JWT_REFRESH_EXPIRATION }}
      GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
      GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
      FACEBOOK_CLIENT_ID: ${{ secrets.FACEBOOK_CLIENT_ID }}
      FACEBOOK_CLIENT_SECRET: ${{ secrets.FACEBOOK_CLIENT_SECRET }}
      MAIL_USERNAME: ${{ secrets.MAIL_USERNAME }}
      MAIL_PASSWORD: ${{ secrets.MAIL_PASSWORD }}
      OAUTH2_REDIRECT_URI: ${{ secrets.OAUTH2_REDIRECT_URI }}
      DB_URL: jdbc:postgresql://localhost:5432/excermol_ci
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      LOG_FILE_PATH: /tmp/application.log

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Run tests
        run: mvn clean verify -B

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: target/surefire-reports/

  docker-build:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t excermol:${{ github.sha }} .